Repository epsagon/epsagon-node-frameworks, pull requests merged in 2020-09, with the labels that each got.

#57 feat(express_next): wrap next middleware in express
  src/trace_context.js
  src/wrappers/express.js
Labels: size/M

#59 fix(node_express): support error-handling middlewares
  src/wrappers/express.js
Labels: size/M

#58 feat(amqp.js): add support for amqp
  README.md
  package-lock.json
  package.json
  src/patcher.js
  src/wrappers/amqp.js
Labels: size/L

#61 fix(http.js): update ignore endpoints to startWith
  src/http.js
  src/wrappers/express.js
  src/wrappers/hapi.js
  src/wrappers/koa.js
Labels: size/S

#60 Ep 4448 support express middlewares in routes
  src/consts/http_methods.js
  src/consts/index.js
  src/wrappers/express.js
Labels: size/M

#62 fix(express_node): support middlewares that passed in http methods
  src/wrappers/express.js
Labels: size/XS

#63 feat(kafka-node.js): support kafka-node
  README.md
  package-lock.json
  package.json
  src/patcher.js
  src/wrappers/kafka-node.js
Labels: size/L

#64 fix(async_hooks_destroy): destroy tracers dict on trace sent
  src/trace_context.js
  src/wrappers/express.js
Labels: size/S

#66 docs(readme): update mongo supported version
  README.md
Labels: size/XS

#67 fix(express.js): don't send empty fields
  src/runners/express.js
Labels: size/S

#68 fix(package.json): bump epsagon version
  package-lock.json
  package.json
Labels: size/XS

#70 feat(http.js): ignore requests by incoming headers
  src/http.js
  src/wrappers/express.js
  src/wrappers/hapi.js
  src/wrappers/koa.js
Labels: size/S

#69 feat(express_route_fix): change route to original path
  src/runners/express.js
Labels: size/M

#71 fix(express_route_url): remove replace function
  src/runners/express.js
Labels: size/XS

#74 feat(tracer.js): get trace url
  README.md
  package-lock.json
  package.json
  src/wrappers/amqp.js
  src/wrappers/amqplib.js
  src/wrappers/bunnybus.js
  src/wrappers/express.js
  src/wrappers/hapi.js
  src/wrappers/kafka-node.js
  src/wrappers/kafkajs.js
  src/wrappers/koa.js
  src/wrappers/pubsub.js
  src/wrappers/sqs-consumer.js
  src/wrappers/ws.js
Labels: size/M

#75 fix(sqs-consumer.js): support batch handler
  README.md
  src/wrappers/sqs-consumer.js
Labels: size/M

#76 fix(package.json): upgrade epsagon version
  package.json
Labels: size/XS
