Repository epsagon/epsagon-node-frameworks, pull requests merged in 2020-04, with the labels that each got.

#28 fix(readme.md): update readme
  .github/CODEOWNERS
  README.md
Labels: size/L

#29 fix(index.d.ts): add index.d.ts file
  src/index.d.ts
Labels: size/S

#30 feat(cw logs identifier): add log id
  package-lock.json
  package.json
  src/runners/express.js
  src/runners/hapi.js
  src/runners/koa.js
Labels: size/XS

#31 feat(cw logs identifier): add config
  README.md
  package-lock.json
  package.json
  src/runners/express.js
  src/runners/hapi.js
  src/runners/koa.js
Labels: size/XS
