Repository epsagon/epsagon-node-frameworks, pull requests merged in 2020-07, with the labels that each got.

#40 fix(hapi.js): support latest hapi
  package.json
  src/wrappers/hapi.js
Labels: size/M

#43 BB v7 compatibility
  README.md
  src/wrappers/bunnybus.js
Labels: size/M

#42 feat(bunnybus.js): add support for bunnybus
  README.md
  src/patcher.js
  src/wrappers/amqplib.js
  src/wrappers/bunnybus.js
Labels: size/L

#44 fix(hapi.js): handle non promise hapi response
  src/wrappers/hapi.js
Labels: size/S

#45 feat(superagent.js): add native support for superagent
  package.json
  src/events/superagent.js
  src/patcher.js
Labels: size/M

#46 docs(README): update link
  README.md
Labels: size/XS

#47 fix(hapi.js): adding ignored plugins
  src/wrappers/hapi.js
Labels: size/M

#48 fix(package.json): update packages
  package-lock.json
  package.json
Labels: size/XS

#49 feat(superagent-wrapper.js): add support for superagent-wrapper
  src/events/superagent-wrapper.js
  src/patcher.js
Labels: size/M
