Repository epsagon/epsagon-node-frameworks, pull requests merged in 2020-08, with the labels that each got.

#50 feat(websocket): add ws instrumentation
  README.md
  package.json
  src/patcher.js
  src/wrappers/ws.js
Labels: size/L

#51 fix(packge.json): update to latest epsagon
  package.json
Labels: size/XS

#53 fix(sqs-consumer): parse queue url
  src/wrappers/sqs-consumer.js
Labels: size/M

#54 fix(express,sqs): verbose logging
  src/wrappers/express.js
  src/wrappers/sqs-consumer.js
Labels: size/M

#55 fix(redis.js): support async redis calls context propagation
  src/events/redis.js
  src/patcher.js
  src/trace_context.js
Labels: size/M

#56 fix(amqplib.js): add debug logs and make it fail-safe
  package.json
  src/wrappers/amqplib.js
Labels: size/M
