Repository epsagon/epsagon-node-frameworks, pull requests merged in 2020-12, with the labels that each got.

#88 fix(ws): add ws promise to pendingevents map
  README.md
  package.json
  src/wrappers/ws.js
Labels: size/S

#89 feat(restify.js): support restify
  README.md
  src/patcher.js
  src/runners/restify.js
  src/wrappers/restify.js
Labels: size/L

#90 Update README with EPSAGON_ALLOW_NO_ROUTE
  README.md
Labels: size/XS

#92 fix(async_hooks): properly remove old tracers
  examples/express_example.js
  src/trace_context.js
Labels: size/XS
