Repository epsagon/epsagon-node-frameworks, pull requests merged in 2020-11, with the labels that each got.

#79 fix(setwarning): update docs & bump epsagon version
  README.md
  package.json
Labels: size/S

#81 fix(express.js): capture exceptions
  src/wrappers/express.js
Labels: size/XS

#82 feat(pacakge.json): bump epsagon version to 1.99.0
  package.json
Labels: size/XS

#83 fix(express.js): capture express body
  src/runners/express.js
Labels: size/XS

#84 Batch processing
  .gitignore
  package.json
  src/index.d.ts
Labels: size/M

#85 fix(batch_processing): release
  README.md
Labels: size/M

#86 fix(batch-processing): post traces
  package.json
Labels: size/XS
