Repository epsagon/epsagon-node-frameworks, pull requests merged in 2021-04, with the labels that each got.

#143 fix(kafka.js): support epsagon events
  src/wrappers/kafkajs.js
Labels: size/XS

#144 Capture express response
  src/wrappers/express.js
Labels: size/S

#145 fix(readme): release version
  README.md
Labels: size/XS

#146 fix(change_node_version): upgrade node version
  package.json
Labels: size/XS

#148 fix(upgrade_epsagon): upgrade epsagon
  package-lock.json
  package.json
Labels: size/XS

#150 Remove fastify body
  src/wrappers/fastify.js
Labels: size/S

#151 fix(update_epsagon): update epsagon version
  package-lock.json
  package.json
Labels: size/XS

#152 feat(kafkajs.js): support eachBatch operations
  src/wrappers/kafkajs.js
Labels: size/M
