Repository epsagon/epsagon-node-frameworks, pull requests merged in 2021-02, with the labels that each got.

#125 fix(failsafe): using debug logs, disabling resource monitor
  .eslintrc
  src/resource_monitor/index.js
  src/resource_monitor/monitor_resource_usage.js
  src/trace_context.js
Labels: size/S

#126 fix(update_epsagon): update epsagon version
  package-lock.json
  package.json
Labels: size/XS

#127 Ep 000 mongo support
  src/events/mongodb.js
  src/patcher.js
Labels: size/L

#128 fix(express.js): skip error reporting with sampling mode
  src/wrappers/express.js
Labels: size/S

#129 Upgrade epsagon node
  package.json
Labels: size/XS

#131 fix(trace context): only initiate tracer context if exists
  src/trace_context.js
Labels: size/XS

#132 feat(fastify.js): add support for fastify
  README.md
  src/patcher.js
  src/runners/fastify.js
  src/wrappers/fastify.js
Labels: size/L

#134 fix(resource-monitor): checking if runner exists operating
  src/trace_context.js
Labels: size/XS

#135 Ep 6042 support express in node 8
  src/wrappers/express.js
Labels: size/M
