Repository epsagon/epsagon-node-frameworks, pull requests merged in 2021-01, with the labels that each got.

#93 fix(bunnybus): fixing logging integration for bunnybus consumers
  .gitignore
  src/wrappers/bunnybus.js
Labels: size/XS

#94 Mysql wrapper - support async hooks in mysql requests
  .gitignore
  src/events/mysql.js
  src/patcher.js
  src/wrappers/express.js
Labels: size/L

#96 feat(package): using latest version
  package.json
Labels: size/XS

#99 fix(memory): tracers index leak in express
  src/trace_context.js
Labels: size/XS

#100 fix(cicd): hotfix - disabling auto release
  .travis.yml
Labels: size/XS

#101 feat(performance): removing tracers every hour
  package-lock.json
  package.json
  src/index.js
  src/resource_monitor.js
  src/trace_context.js
Labels: size/M

#103 feat(performance): added ttl checks
  src/resource_monitor/clear_tracers.js
  src/resource_monitor/index.js
  src/resource_monitor/monitor_resource_usage.js
  src/trace_context.js
Labels: size/M

#105 feat(performance): added disableAll, express support
  src/index.js
  src/trace_context.js
  src/wrappers/express.js
Labels: size/M

#104 fix(trace_context): improve async reference handling
  src/events/mysql.js
  src/trace_context.js
  src/wrappers/express.js
Labels: size/M

#106 feat(performance): using console.log for hammers
  .eslintrc
  src/resource_monitor/clear_tracers.js
  src/resource_monitor/monitor_resource_usage.js
  src/trace_context.js
Labels: size/S

#108 feat(performance): using console.log for hammers
  src/resource_monitor/monitor_resource_usage.js
Labels: size/XS

#110 feat(patcher): enabling whitelist mode
  src/patcher.js
Labels: size/M

#111 feat(performance): updated cpu/mem sampling
  package-lock.json
  package.json
  src/resource_monitor/monitor_resource_usage.js
  src/resource_monitor/utils.js
  src/trace_context.js
Labels: size/M

#112 fix(express wrapper): add setAsyncReference
  src/wrappers/express.js
Labels: size/XS

#114 feat(performance): check if unpatched before disabling
  src/resource_monitor/monitor_resource_usage.js
Labels: size/XS

#115 fix(mysql_and_redis): remove regular clear of tracers dict
  src/events/mysql.js
  src/trace_context.js
  src/wrappers/express.js
Labels: size/S

#116 fix(async_hooks): deal with recycled async IDs
  src/events/mysql.js
  src/events/redis.js
  src/trace_context.js
  src/wrappers/express.js
Labels: size/L

#117 feat(tagging): added tagging for removed tracers
  src/trace_context.js
Labels: size/XS

#118 feat(tagging): added tagging for removed tracers - revert
  src/trace_context.js
Labels: size/XS

#119 fix(async_hooks): deal with recycled async IDs
  src/events/mysql.js
  src/events/redis.js
  src/trace_context.js
  src/wrappers/express.js
Labels: size/L

#120 feat(tagging): added tagging for removed tracers
  src/trace_context.js
Labels: size/XS

#123 fix(async_hooks): initialize async hooks once on startup
  src/index.js
  src/trace_context.js
  src/wrappers/amqp.js
  src/wrappers/amqplib.js
  src/wrappers/bunnybus.js
  src/wrappers/express.js
  src/wrappers/hapi.js
  src/wrappers/kafka-node.js
  src/wrappers/kafkajs.js
  src/wrappers/koa.js
  src/wrappers/nats.js
  src/wrappers/pubsub.js
  src/wrappers/restify.js
  src/wrappers/sqs-consumer.js
  src/wrappers/ws.js
Labels: size/M

#124 fix(async_hooks): initialize async hooks on patcher
  src/index.js
  src/patcher.js
Labels: size/XS

#122 fix(performance): missing linked asyncIds - user tracerObj for linking
  src/events/mysql.js
  src/events/redis.js
  src/trace_context.js
  src/wrappers/express.js
Labels: size/M
