Repository epsagon/epsagon-node-frameworks, pull requests merged in 2021-03, with the labels that each got.

#136 fix(http.js): ignore static files
  src/http.js
Labels: size/S

#137 fix(hapi): set main reference for trace context
  src/wrappers/amqplib.js
  src/wrappers/bunnybus.js
  src/wrappers/hapi.js
Labels: size/XS

#139 fix(fastify.js): fix reply end handling
  src/wrappers/fastify.js
Labels: size/M

#140 fix(bunnybus): missing traces
  src/wrappers/amqplib.js
  src/wrappers/bunnybus.js
  src/wrappers/hapi.js
Labels: size/S

#142 Ep 6341 - remove tracer from amqplib
  src/wrappers/amqplib.js
Labels: size/S
